image:
  repository: registry.gitlab.com/cryptophobic/ml-ops-ci-cd-classes/digits-inference
  tag: "0.1.0"
  pullPolicy: IfNotPresent

replicaCount: 1

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    memory: 512Mi

mlflow:
  trackingUri: http://mlflow.mlflow.svc.cluster.local:5000
  s3EndpointUrl: http://minio.mlflow.svc.cluster.local:9000
  awsAccessKeyId: mlflow
  awsSecretAccessKey: mlflow-secret-key
  awsRegion: us-east-1

model:
  name: digits-classifier
  stage: Production

drift:
  threshold: "3.0"

serviceMonitor:
  enabled: true
  interval: 15s
  namespace: monitoring
  labels:
    release: kube-prometheus-stack

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8000"
  prometheus.io/path: "/metrics"